platform: linux
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/cf-cli
    tag: e1ffec0d1940706f157a8c1e0ab8131b7084fa1c
inputs:
  - name: git-main
    path: src
params:
  CF_API: https://api.london.cloud.service.gov.uk
  CF_USERNAME: ((paas-username))
  CF_PASSWORD: ((paas-password))

run:
  dir: src
  path: sh
  args:
    - "-c"
    - |
      set -eu

      cf api "$CF_API"
      cf auth
      cf target -o "$CF_ORG" -s "$CF_SPACE"
      cf push --strategy rolling
      cf map-route $CF_APP_NAME london.cloudapps.digital --hostname "$HOSTNAME"
